name: Scrape Brave Frontier on Github Actions
on:
  push:
    branches:
      - master
  schedule:
    # Run at 23:59 once every three days
    - cron: '59 23 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '>=12.14.1'
    - name: Install dependecies
      run: npm ci
    - name: Store scraping omni units into raw file
      run: npm run omniunits:raw
    - name: Store scrapping dbbs into raw file
      run: npm run dbbs:raw
    - name: Upload omniunits thumbnails to Cloudinary
      run: npm run omniunits:thumbnails
      env:
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
    - name: Upload omniunits artworks to Cloudinary
      run: npm run omniunits:artworks
      env:
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
    - name: Deploy to vercel
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}
        vercel-project-id: ${{ secrets.PROJECT_ID}}
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.MY_EMAIL }}
        git config --local user.name "Satya Kresna on Github Actions"
        git add .
        git commit -m "chore: update scrape data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}