name: Scrape Brave Frontier on Github Actions
on:
  push:
    branches:
      - master
  schedule:
    # Run at 23:59 on every day
    - cron: '59 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '>=12.14.1'
    - name: Install dependecies
      run: npm ci
    - name: Store scraping omni units into raw file
      run: npm run omniunits:raw
    # - name: Download unit artworks
    #   run: npm run omniunits:artworks
    # - name: Download unit thumbnails
    #   run: npm run omniunits:thumbnails
    - name: Build data
      run: | 
      npm run omniunits:build
      npm run dbbs:raw
    - name: Deploy to vercel
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}
        vercel-project-id: ${{ secrets.PROJECT_ID}}
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.MY_EMAIL }}
        git config --local user.name "Satya Kresna on Github Actions"
        git add .
        git commit -m "chore: update scrape data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}